TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

INC += ntndArrayConverter.h

LIBRARY_IOC += ntndArrayConverter
ntndArrayConverter_SRCS += ntndArrayConverter.cpp
ntndArrayConverter_LIBS += pvData
ntndArrayConverter_LIBS += nt

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

